services:
  
  # PHP Service
  app:
    build:
      context: ./build
      dockerfile: Dockerfile_app
    image: php-laravel-app
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
      #- web-root:/var/www
      - ./app:/var/www
      - ./certs/ssh:/home/www/.ssh
      - ./config/laravel/.env.dev:/var/www/.env
      - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini
      - ./logs/laravel:/var/www/storage/logs
      - ./scripts:/home/www/scripts
    networks:
      - app-network

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    depends_on:
      - app
    restart: unless-stopped
    tty: true
    ports:
      - 6080:80
      #- 443:443
    volumes:
      #- web-root:/var/www
      - ./app:/var/www
      - ./config/nginx/conf.d/:/etc/nginx/conf.d/
      - ./logs/nginx:/var/log/nginx
      # - certbot-etc:/etc/letsencrypt
      # - certbot-var:/var/lib/letsencrypt
      # - dhparam:/etc/ssl/certs
    networks:
      - app-network

  # MySQL Service
  db:
    image: mariadb
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      SERVICE_NAME: mysql
      SERVICE_TAGS: dev
    volumes:
      - dbdata:/var/lib/mysql/
      - ./config/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

  # Adminer Service
  adminer:
    container_name: adminer
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - app-network

  # Composer Service
  composer:
    container_name: composer
    image: composer
    depends_on: 
      - app
    volumes:
      #- web-root:/app
      - ./app:/app
    working_dir: /app
    command: composer install
  
  # Nodejs Service
  node:
    container_name: node
    image: node
    depends_on: 
      - app
    volumes:
      #- web-root:/app
      - ./app:/app
    working_dir: /app
    command: npm install

  #Certbot Service
  # certbot:
  #   image: certbot/certbot
  #   container_name: certbot
  #   depends_on:
  #     - webserver
  #   volumes:
  #     - web-root:/var/www/html
  #     - certbot-etc:/etc/letsencrypt
  #     - certbot-var:/var/lib/letsencrypt
  #     - ./logs/certbot:/var/log/letsencrypt
  #   #command: certonly --webroot --webroot-path=/var/www/html --email www@vantoose.ru --agree-tos --no-eff-email --staging -d vantoose.ru -d www.vantoose.ru
  #   command: certonly --webroot --webroot-path=/var/www/html --email www@vantoose.ru --agree-tos --no-eff-email --force-renewal -d vantoose.ru -d www.vantoose.ru

# Volumes
volumes:
  dbdata:
  # web-root:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ./app
  #     o: bind
  # certbot-etc:
  # certbot-var:
  # dhparam:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     device: ./certs/dhparam
  #     o: bind

# Docker Networks
networks:
  app-network:
    driver: bridge